version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: aether
    binary: aether
    main: .
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_CFLAGS=-O2 -D__BLST_PORTABLE__
      - CGO_ENABLED=1
      # Darwin
      - CC_darwin_amd64=o64-clang
      - CXX_darwin_amd64=o64-clang++
      - CC_darwin_arm64=oa64-clang
      - CXX_darwin_arm64=oa64-clang++
      # Linux
      - CC_linux_amd64=x86_64-linux-gnu-gcc
      - CXX_linux_amd64=x86_64-linux-gnu-g++
      - CC_linux_arm64=aarch64-linux-gnu-gcc
      - CXX_linux_arm64=aarch64-linux-gnu-g++
      # Windows (llvm-mingw toolchains)
      - CC_windows_amd64=/llvm-mingw/bin/x86_64-w64-mingw32-gcc
      - CXX_windows_amd64=/llvm-mingw/bin/x86_64-w64-mingw32-g++
      - CC_windows_arm64=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
      - CXX_windows_arm64=/llvm-mingw/bin/aarch64-w64-mingw32-g++
      - 'CC={{ index .Env (print "CC_" .Os "_" .Arch) }}'
      - 'CXX={{ index .Env (print "CXX_" .Os "_" .Arch) }}'
    flags:
      - -mod=readonly
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: aether
    ids:
      - aether
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: false
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: 'Performance improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 20
    - title: Other work
      order: 999

release:
  github:
    owner: bjartek
    name: aether
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## Aether {{ .Tag }} ({{ .Date }})
    
    Welcome to this new release of Aether!
