on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: ci
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5

  tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - uses: zencargo/github-action-go-mod-tidy@v1
        with:
          go-version: "1.25"

  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - run: make test-report
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-result.xml

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - run: make coveralls
      - uses: shogo82148/actions-goveralls@v1
        if: always()
        with:
          path-to-profile: profile.cov

  semantic-release:
    runs-on: ubuntu-latest
    needs: [lint, tidy, test, coverage]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      
      - name: Install semantic-release
        run: |
          npm install -g semantic-release@24 \
            @semantic-release/github@11
      
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
